export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const ADMIN = '/admin';
export const TRAINER = '/trainer';
export const TRAINEE = '/trainee';
export const PASSWORD_RESET = '/resetpassword';
export const CART = '/cart';
export const MODULES = '/module';
export const PROFILE = '/profile';
export const ASSESSMENTS = '/assessments';
export const HIRED = '/hired';
export const INTERVIEWS = '/interviews';
export const PAYMENT = '/payment';
export const LIVE_SUPPORT ='/livesupport'
