export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const ADMIN = '/admin';
export const TRAINER = '/trainer';
export const TRAINEE = '/trainee';
export const PASSWORD_RESET = '/resetpassword';
export const SCHEDULE = '/scheduleclass';
export const MODULES = '/module';
export const PROFILE = '/profile';
export const LIVE_CLASS = '/liveclass';
export const ASSESSMENTS = '/final_assessment';
export const HIRE = '/hire';
export const HIRED = '/hired';
export const INTERVIEWS = '/interviews';
export const PAYMENT = '/payment';
export const LIVE_SUPPORT ='/support';
export const SUCCESS_PAGE = '/success';
export const CHAT ='/chat';
export const ENROLLED = '/enrolled';
export const ACTIVE_USERS = '/act-users';
export const ANNOUNCEMENTS = '/announcements';
export const SSESSIONS = '/sessions';
export const N_TRAINERS = '/n-trainers';
export const T_MODULES = '/t-modules';
export const Live_CLASSES = '/liveclass';
export const TR_ANOUNC = '/tr-announc';
export const TN_ANOUNC = '/tN-announc'

