export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const ADMIN = '/admin';
export const TRAINER = '/trainer';
export const TRAINEE = '/trainee';
export const PASSWORD_RESET = '/resetpassword';
export const SCHEDULE = '/scheduleclass';
export const QUIZ = '/quiz';
export const MODULES = '/module';
export const PROFILE = '/profile';
export const LIVE_CLASS = '/liveclass';
export const ASSESSMENTS = '/assessments';
export const SESSIONS = '/sessions';
export const FINALASSESS = '/final';
export const TEST = '/test';
export const HIRE = '/hire';
export const HIRED = '/hired';
export const INTERVIEWS = '/interviews';
export const PAYMENT = '/payment';
export const LIVE_SUPPORT ='/support';
export const SUCCESS_PAGE = '/success';
export const CHAT ='/chat'

